name: piano
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.2 <4.0.0"
  flutter: ">=3.10.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  flutter_midi_pro: 
    git:
      url: https://github.com/rrafush/flutter_midi_pro
      ref: play-feedback
  flutter_svg: ^2.0.7
  google_fonts: ^5.1.0
  # flutter_midi:
  #   git:
  #     url: https://github.com/kNoAPP/flutter_midi
  #     ref: velocity
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/svg/
    - assets/png/
